### PR TITLE
Evaluates NodeList and HTMLCollection properly

### LINKED ISSUE #2: $(element.children) does not work properly
Doc generates an Array with only one element and this one is an NodeList.

Doc returns a NodeList element when given `$(element.children)`. The expected behaviour would be returning the children elements as an Array.

### PR DESCRIPTION
**Pull request by danielyudiushino**
👍   @diegocesar
Closes #2 
# Changelog
- When passing an instance of `NodeList` to `$()`, evaluates it as an Array and filters non-element nodes
- When passing an instance of `HTMLColleciton` to `$()`, evaluates it as an Array.

@leocwolter @luiz

### CODE REVIEW

File: doc.js [hunk 1]
```diff
@@ -49,12 +49,28 @@ define('doc', ['event'], function(event) {
...
 		var selectedElements = [];
 
-		if (elements){
+		if (elements) {
 			if (elements instanceof Array) {
 				selectedElements = elements;
+			} else if (elements instanceof HTMLCollection) {
+				selectedElements = convertHtmlCollectionToArray(elements);
+			} else if (elements instanceof NodeList) {
+				selectedElements = convertNodeListToArray(elements);
```
Comment (mottam) [inline doc.js:101]: Why don't you use `Array.prototype.slice.call(elements)` for both cases? The methods `convertNodeListToArray` and `convertHtmlCollectionToArray` are unnecessary.

@tcelestino @mottam

Comment (rapahaeru) [reply doc.js:101]: `convertHtmlCollectionToArray` existed before and seems fair for me to exist, even though it is as simple as `Array.prototype.slice.call(elements)`. IMHO, it makes the code more readable.

`convertNodeListToArray` is not exactly the same, as it filters elements too, so I prefer to keep both.

@luiz

**Review by diegocesar — APPROVED** [review]
